---
title: "DSlecture10"
author: "Hening cui"
date: "2021/10/12"
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## group_by

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup(month)
```
## counting things

count month observation

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())
```

we can use `count()`

```{r}
weather_df %>% 
  count(month, name = "n_obs")
```

never use bases r table function

```{r,eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```
not df, cannot use

other counting function

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarise(
    n_obs = n(),
    n_days = n_distinct(date)
  )
```

